### ISSUE TITLE
Version 1.1.0 doesn't work on framework 4.8

### ISSUE THREAD

**Issue by YuriyZaletskyy** [sungaila/PDFtoZPL#1]
Hi,
first of all want to thank you for wonderful library. Your efforts are worthy of a lot of appraisal ( including financial ). Please put somewhere on readme section paypal link or something similar.
Want to say, that I have a need to use your library for framework 4.8, but once I do this, I can't get conversion from PDF to ZPL.

Here is the error message I'm getting:
Failed to convert file.
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at PDFtoZPL.PdfiumViewer.NativeMethods.Imports.FPDF_AddRef()
   at PDFtoZPL.PdfiumViewer.NativeMethods.FPDF_AddRef()
   at PDFtoZPL.PdfiumViewer.PdfLibrary.EnsureLoaded()
   at PDFtoZPL.PdfiumViewer.PdfFile..ctor(Stream stream, String password)
   at PDFtoZPL.PdfiumViewer.PdfDocument..ctor(Stream stream, String password)
   at PDFtoZPL.PdfiumViewer.PdfDocument.Load(Stream stream, String password)
   at PDFtoZPL.Conversion.ConvertPdfPage(Stream pdfStream, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height)
   at PdfToZPLConsole.Program.Main(String[] args) in D:\SourceCode\PdfToZPL\PDFtoZPL\PdfToZPLConsole\Program.cs:line 34

But if I use 1.0.0 version, such an error doesn't appear.

**Comment by sungaila** [comment]
Hi Yuriy,

thank you for submitting an issue. I fixed this in [the newest NuGet package](https://www.nuget.org/packages/PDFtoZPL/1.2.0-preview). Please let me know if this resolves your problem.

I don't accept any donations as this project is just [PdfiumViewer](https://github.com/pvginkel/PdfiumViewer) with some extra code. But i am grateful that you find a use for it! 🙂
