### ISSUE TITLE
PDFtoImage: System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')

### ISSUE THREAD

**Issue by thevarium** [sungaila/PDFtoZPL#20]
**Describe the bug**
Getting an error when trying run a single-file app. To get the path of the .so files in included, it uses this to get the directory/path its running in:

Path.GetDirectoryName(new Uri(Assembly.GetExecutingAssembly().GetName(false).CodeBase!).LocalPath)!;

Using member 'System.Reflection.AssemblyName.CodeBase.get' which has 'RequiresAssemblyFilesAttribute' can break functionality when embedded in a single-file app. The code will return an empty string for assemblies embedded in a single-file app, but for single file exe, like what we have, it causes it to break

**Stack trace**
/PdfZplCli_local -d 203 -w 406 -h 254 -g -e b64 -b `cat ./img.txt`
Unhandled exception. System.TypeInitializationException: The type initializer for 'PDFtoImage.PdfiumViewer.NativeMethods' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
   at System.Uri..ctor(String uriString)
   at PDFtoImage.PdfiumViewer.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at PDFtoImage.PdfiumViewer.NativeMethods.FPDF_InitLibrary()
   at PDFtoImage.PdfiumViewer.PdfLibrary..ctor()
   at PDFtoImage.PdfiumViewer.PdfLibrary.EnsureLoaded()
   at PDFtoImage.PdfiumViewer.PdfFile..ctor(Stream stream, String password, Boolean disposeStream)
   at PDFtoImage.PdfiumViewer.PdfDocument..ctor(Stream stream, String password, Boolean disposeStream)
   at PDFtoImage.PdfiumViewer.PdfDocument.Load(Stream stream, String password, Boolean disposeStream)
   at PDFtoImage.Conversion.ToImages(Stream pdfStream, Boolean leaveOpen, String password, Int32 dpi, Nullable`1 width, Nullable`1 height, Boolean withAnnotations, Boolean withFormFill)+MoveNext()
   at PDFtoZPL.Conversion.ConvertPdf(Stream pdfStream, Boolean leaveOpen, String password, Int32 dpi, Nullable`1 width, Nullable`1 height, Boolean withAnnotations, Boolean withFormFill, BitmapEncodingKind encodingKind, Boolean graphicFieldOnly)+MoveNext()
   at PDFtoZPL.Conversion.ConvertPdf(Byte[] pdfAsByteArray, String password, Int32 dpi, Nullable`1 width, Nullable`1 height, Boolean withAnnotations, Boolean withFormFill, BitmapEncodingKind encodingKind, Boolean graphicFieldOnly)+MoveNext()
   at PDFtoZPL.Conversion.ConvertPdf(String pdfAsBase64String, String password, Int32 dpi, Nullable`1 width, Nullable`1 height, Boolean withAnnotations, Boolean withFormFill, BitmapEncodingKind encodingKind, Boolean graphicFieldOnly)+MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   at PdfZplCli.Program.Main(String[] args)
Abort trap: 6

**OS information**
- Which OS? Linux and macOS
- What architecture? x86 and x64
- What OS version? OSX 12.4 on Mac & Debian Buster for Linux

**Sample PDFs/bitmaps/files**
I have the cli file but it is too large to upload here but I can send it if you have a method to do so.

**Comment by thevarium** [comment]
`Console.Write(Path.GetDirectoryName(new Uri(Assembly.GetExecutingAssembly().GetName(false).CodeBase).LocalPath));
-> /Users/j0s0r6g/RiderProjects/PdfZplCli/PdfZplCli/bin/Debug/net6.0`

`Console.Write(Path.GetDirectoryName(Process.GetCurrentProcess().MainModule.FileName));
-> /Users/j0s0r6g/RiderProjects/PdfZplCli/PdfZplCli/bin/Debug/net6.0`

However in single file publish, `new Uri(Assembly.GetExecutingAssembly().GetName(false).CodeBase).LocalPath` causes an error because `Assembly.GetExecutingAssembly().GetName(false).CodeBase` returns a null when trying to get the path of the working directory. so I wasnt able to get a output when running single file on osx-x64

Path.GetDirectoryName(Process.GetCurrentProcess().MainModule.FileName) seems to return the same working directory.
`Console.Write(Path.GetDirectoryName(Process.GetCurrentProcess().MainModule.FileName));
-> /Users/j0s0r6g/RiderProjects/PdfZplCli/PdfZplCli/bin/Release/net6.0/osx-x64/publish`

so I think that `Path.GetDirectoryName(new Uri(Assembly.GetExecutingAssembly().GetName(false).CodeBase).LocalPath)` is the main cause of the error since it is returning null

**Comment by thevarium** [comment]
@sungaila I should have mentioned that .net core 3.1 works fine, but this error only started appearing once we moved to .NET 5/6. We are trying to use .net5/6 so we can use R2R (ready to run/ ahead of time compilation) in an attempt to improve performance and shorten the startup time. The service works great at smaller scale but when we test it at production scale (~300 TPS) we have massive CPU usage (would require +80 cores) and hoping that using R2R will help with the high CPU issues.

**Comment by sungaila** [comment]
@thevarium [PDFtoZPL 3.2.1](https://www.nuget.org/packages/PDFtoZPL/3.2.1) just dropped, please give it a try!

**Comment by thevarium** [comment]
@sungaila Thank you for the amazing support once again. We tested the change and it is now working without error and allowed us to slightly improve response times of our service. Thank you again.
