### ISSUE TITLE
The type initializer for 'PDFtoImage.PdfiumViewer.NativeMethods' threw an exception.

### ISSUE THREAD

**Issue by CursedMun** [sungaila/PDFtoZPL#4]
Im getting this error when trying to convert.

Code ->
```
using var fs = new FileStream(filePath, FileMode.Open, FileAccess.Read);
string s = PDFtoZPL.Conversion.ConvertPdfPage(fs);
Teste.SendStringToPrinter(printer, s);
```
exeption->
`An attempt was made to load a program with an incorrect format. (0x8007000B)`
StackTrace->
```
   at PDFtoImage.PdfiumViewer.NativeMethods.FPDF_InitLibrary()
   at PDFtoImage.PdfiumViewer.PdfLibrary..ctor()
   at PDFtoImage.PdfiumViewer.PdfLibrary.EnsureLoaded()
   at PDFtoImage.PdfiumViewer.PdfFile..ctor(Stream stream, String password)
   at PDFtoImage.PdfiumViewer.PdfDocument..ctor(Stream stream, String password)
   at PDFtoImage.PdfiumViewer.PdfDocument.Load(Stream stream, String password)
   at PDFtoImage.Conversion.ToImage(Stream pdfStream, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height)
   at PDFtoZPL.Conversion.ConvertPdfPage(Stream pdfStream, String password, Int32 page, Int32 dpi, Nullable`1 width, Nullable`1 height)
   at AbcPrint.Core.ViewModels.PrintViewModel.PrintPDF(String printer, String paperName, String filePath, Int32 copies) in C:\Users\ABC-DSI1\source\repos\AbcBraga\AbcPrint.WPF\AbcPrint.Core\ViewModels\PrintViewModel.cs:line 428
```
Windows 10
.net core 5

**Update:**
Using it on Library class results in the following error

**Comment by sungaila** [comment]
Hi CursedMun,

is your project AbcPrint compiled as 32 bit but running on a 64 bit Windows by any chance?
