### ISSUE TITLE
Unable to find an entry point named 'FPDF_InitLibrary' in DLL 'pdfium'.

### ISSUE THREAD

**Issue by danscan1712** [sungaila/PDFtoZPL#53]
### PDFtoZPL version

5.0.1

### OS

Windows

### OS version

Windows 11

### Architecture

x64

### Framework

.NET (Core)

### Detailed bug report

Attempting to change a pdf of a shipping label to a zpl.  
Updated all libraries to latest version including secondary dlls like PDFium.Linux, macOS, Win32

Stack: 
   at PDFtoImage.Internals.NativeMethods.Imports.FPDF_InitLibrary()
   at PDFtoImage.Internals.NativeMethods.FPDF_InitLibrary()
   at PDFtoImage.Internals.PdfLibrary.EnsureLoaded()
   at PDFtoImage.Internals.PdfFile..ctor(Stream stream, String password, Boolean disposeStream)
   at PDFtoImage.Internals.PdfDocument..ctor(Stream stream, String password, Boolean disposeStream)
   at PDFtoImage.Internals.PdfDocument.Load(Stream stream, String password, Boolean disposeStream)
   at PDFtoImage.Conversion.ToImage(Stream pdfStream, Boolean leaveOpen, String password, Int32 page, RenderOptions options)
   at PDFtoZPL.Conversion.ConvertPdfPage(Stream pdfStream, Boolean leaveOpen, String password, Int32 page, PdfOptions pdfOptions, ZplOptions zplOptions)
   at PDFtoZPL.Conversion.ConvertPdfPage(Byte[] pdfAsByteArray, String password, Int32 page, PdfOptions pdfOptions, ZplOptions zplOptions)
   at PDFtoZPL.Conversion.ConvertPdfPage(String pdfAsBase64String, String password, Int32 page, PdfOptions pdfOptions, ZplOptions zplOptions) 

I coded two different versions with both having the same result:
```
var zpl = PDFtoZPL.Conversion.ConvertPdfPage(response.labelImage);
var stringArray = PDFtoZPL.Conversion.ConvertPdfPage(Convert.FromBase64String(response.labelImage));
```[PdfLabel.txt](https://github.com/sungaila/PDFtoZPL/files/15315002/PdfLabel.txt)
response.labelImage in attachment


### Generated ZPL code

_No response_

**Comment by sungaila** [comment]
Hi @danscan1712,

where is the pdfium.dll in your output folder? Is it in the runtimes folder or in the root folder?

**Comment by sungaila** [comment]
Please reopen this issue if your problem is still unfixed.
